package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbClientes generated by hbm2java
 */
@Entity
@Table(name="tb_clientes"
    ,catalog="db_murilo_resende"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cpf"), @UniqueConstraint(columnNames="rg"), @UniqueConstraint(columnNames="cep")} 
)
public class TbClientes  implements java.io.Serializable {


     private int idCliente;
     private String nmCliente;
     private String cpf;
     private Date dtNascimento;
     private String telefone;
     private char ativo;
     private String rg;
     private String cep;
     private String sexo;
     private String observacoes;
     private String cidade;
     private String estado;
     private String bairro;
     private String email;
     private String endereco;

    public TbClientes() {
    }

	
    public TbClientes(int idCliente, String nmCliente, String cpf, char ativo, String estado) {
        this.idCliente = idCliente;
        this.nmCliente = nmCliente;
        this.cpf = cpf;
        this.ativo = ativo;
        this.estado = estado;
    }
    public TbClientes(int idCliente, String nmCliente, String cpf, Date dtNascimento, String telefone, char ativo, String rg, String cep, String sexo, String observacoes, String cidade, String estado, String bairro, String email, String endereco) {
       this.idCliente = idCliente;
       this.nmCliente = nmCliente;
       this.cpf = cpf;
       this.dtNascimento = dtNascimento;
       this.telefone = telefone;
       this.ativo = ativo;
       this.rg = rg;
       this.cep = cep;
       this.sexo = sexo;
       this.observacoes = observacoes;
       this.cidade = cidade;
       this.estado = estado;
       this.bairro = bairro;
       this.email = email;
       this.endereco = endereco;
    }
   
     @Id 

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nm_cliente", nullable=false, length=100)
    public String getNmCliente() {
        return this.nmCliente;
    }
    
    public void setNmCliente(String nmCliente) {
        this.nmCliente = nmCliente;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_nascimento", length=10)
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }

    
    @Column(name="telefone", length=20)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="rg", unique=true, length=11)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="cep", unique=true, length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="sexo", length=9)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="observacoes")
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    
    @Column(name="cidade", length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="estado", nullable=false, length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="bairro", length=100)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="endereco", length=150)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


