package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbFormasPagamento generated by hbm2java
 */
@Entity
@Table(name="tb_formas_pagamento"
    ,catalog="db_murilo_resende"
)
public class TbFormasPagamento  implements java.io.Serializable {


     private int idFormaPagamento;
     private String descricao;
     private String tipoTransacao;
     private int prazoRecebimento;
     private double taxaPorcentagem;
     private String parcelamento;
     private Character ativo;

    public TbFormasPagamento() {
    }

	
    public TbFormasPagamento(int idFormaPagamento, String descricao) {
        this.idFormaPagamento = idFormaPagamento;
        this.descricao = descricao;
    }
    public TbFormasPagamento(int idFormaPagamento, String descricao, String tipoTransacao, int prazoRecebimento, double taxaPorcentagem, String parcelamento, Character ativo) {
       this.idFormaPagamento = idFormaPagamento;
       this.descricao = descricao;
       this.tipoTransacao = tipoTransacao;
       this.prazoRecebimento = prazoRecebimento;
       this.taxaPorcentagem = taxaPorcentagem;
       this.parcelamento = parcelamento;
       this.ativo = ativo;
    }
   
     @Id 

    
    @Column(name="id_forma_pagamento", unique=true, nullable=false)
    public int getIdFormaPagamento() {
        return this.idFormaPagamento;
    }
    
    public void setIdFormaPagamento(int idFormaPagamento) {
        this.idFormaPagamento = idFormaPagamento;
    }

    
    @Column(name="descricao", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="tipo_transacao", length=50)
    public String getTipoTransacao() {
        return this.tipoTransacao;
    }
    
    public void setTipoTransacao(String tipoTransacao) {
        this.tipoTransacao = tipoTransacao;
    }

    
    @Column(name="prazo_recebimento")
    public int getPrazoRecebimento() {
        return this.prazoRecebimento;
    }
    
    public void setPrazoRecebimento(int prazoRecebimento) {
        this.prazoRecebimento = prazoRecebimento;
    }

    
    @Column(name="taxa_porcentagem", precision=5)
    public double getTaxaPorcentagem() {
        return this.taxaPorcentagem;
    }
    
    public void setTaxaPorcentagem(double taxaPorcentagem) {
        this.taxaPorcentagem = taxaPorcentagem;
    }

    
    @Column(name="parcelamento", length=10)
    public String getParcelamento() {
        return this.parcelamento;
    }
    
    public void setParcelamento(String parcelamento) {
        this.parcelamento = parcelamento;
    }

    
    @Column(name="ativo", length=1)
    public Character getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }




}


