package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbProdutos generated by hbm2java
 */
@Entity
@Table(name="tb_produtos"
    ,catalog="db_murilo_resende"
)
public class TbProdutos  implements java.io.Serializable {


     private int idProduto;
     private String nmProduto;
     private String descricao;
     private double preco;
     private Character ativo;
     private String categoria;
     private String sabor;

    public TbProdutos() {
    }

	
    public TbProdutos(int idProduto, String nmProduto) {
        this.idProduto = idProduto;
        this.nmProduto = nmProduto;
    }
    public TbProdutos(int idProduto, String nmProduto, String descricao, double preco, Character ativo, String categoria, String sabor) {
       this.idProduto = idProduto;
       this.nmProduto = nmProduto;
       this.descricao = descricao;
       this.preco = preco;
       this.ativo = ativo;
       this.categoria = categoria;
       this.sabor = sabor;
    }
   
     @Id 

    
    @Column(name="id_produto", unique=true, nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="nm_produto", nullable=false, length=100)
    public String getNmProduto() {
        return this.nmProduto;
    }
    
    public void setNmProduto(String nmProduto) {
        this.nmProduto = nmProduto;
    }

    
    @Column(name="descricao", length=65535)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="preco", precision=10)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

    
    @Column(name="ativo", length=1)
    public Character getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="categoria", length=50)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="sabor", length=50)
    public String getSabor() {
        return this.sabor;
    }
    
    public void setSabor(String sabor) {
        this.sabor = sabor;
    }




}


