package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbUsuarios generated by hbm2java
 */
@Entity
@Table(name="tb_usuarios"
    ,catalog="db_murilo_resende"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class TbUsuarios  implements java.io.Serializable {


     private int idUsuario;
     private String nmUsuario;
     private String cpf;
     private String nivel;
     private Date dtNascimento;
     private String senha;
     private Character ativo;

    public TbUsuarios() {
    }

	
    public TbUsuarios(int idUsuario, String nmUsuario, String cpf, String senha) {
        this.idUsuario = idUsuario;
        this.nmUsuario = nmUsuario;
        this.cpf = cpf;
        this.senha = senha;
    }
    public TbUsuarios(int idUsuario, String nmUsuario, String cpf, String nivel, Date dtNascimento, String senha, Character ativo) {
       this.idUsuario = idUsuario;
       this.nmUsuario = nmUsuario;
       this.cpf = cpf;
       this.nivel = nivel;
       this.dtNascimento = dtNascimento;
       this.senha = senha;
       this.ativo = ativo;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nm_usuario", nullable=false, length=100)
    public String getNmUsuario() {
        return this.nmUsuario;
    }
    
    public void setNmUsuario(String nmUsuario) {
        this.nmUsuario = nmUsuario;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="nivel", length=20)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_nascimento", length=10)
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }

    
    @Column(name="senha", nullable=false)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="ativo", length=1)
    public Character getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }




}


