package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbVendas generated by hbm2java
 */
@Entity
@Table(name="tb_vendas"
    ,catalog="db_murilo_resende"
)
public class TbVendas  implements java.io.Serializable {


     private int idVenda;
     private TbClientes tbClientes;
     private TbFormasPagamento tbFormasPagamento;
     private TbUsuarios tbUsuarios;
     private Date dtVenda;
     private double total;
     private String status;
     private String observacoes;

    public TbVendas() {
    }

	
    public TbVendas(int idVenda) {
        this.idVenda = idVenda;
    }
    public TbVendas(int idVenda, TbClientes tbClientes, TbFormasPagamento tbFormasPagamento, TbUsuarios tbUsuarios, Date dtVenda, double total, String status, String observacoes) {
       this.idVenda = idVenda;
       this.tbClientes = tbClientes;
       this.tbFormasPagamento = tbFormasPagamento;
       this.tbUsuarios = tbUsuarios;
       this.dtVenda = dtVenda;
       this.total = total;
       this.status = status;
       this.observacoes = observacoes;
    }
   
     @Id 

    
    @Column(name="id_venda", unique=true, nullable=false)
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente")
    public TbClientes getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(TbClientes tbClientes) {
        this.tbClientes = tbClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_forma_pagamento")
    public TbFormasPagamento getTbFormasPagamento() {
        return this.tbFormasPagamento;
    }
    
    public void setTbFormasPagamento(TbFormasPagamento tbFormasPagamento) {
        this.tbFormasPagamento = tbFormasPagamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_venda", length=10)
    public Date getDtVenda() {
        return this.dtVenda;
    }
    
    public void setDtVenda(Date dtVenda) {
        this.dtVenda = dtVenda;
    }

    
    @Column(name="total", precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="observacoes", length=65535)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }




}


