package bean;
// Generated 06/10/2025 07:56:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="tb_vendas_produtos"
    ,catalog="db_murilo_resende"
)
public class TbVendasProdutos  implements java.io.Serializable {


     private int idVendasProdutos;
     private TbProdutos tbProdutos;
     private TbVendas tbVendas;
     private int quantidade;
     private double valorUnitario;
     private double desconto;
     private String observacoes;

    public TbVendasProdutos() {
    }

	
    public TbVendasProdutos(int idVendasProdutos) {
        this.idVendasProdutos = idVendasProdutos;
    }
    public TbVendasProdutos(int idVendasProdutos, TbProdutos tbProdutos, TbVendas tbVendas, int quantidade, double valorUnitario, double desconto, String observacoes) {
       this.idVendasProdutos = idVendasProdutos;
       this.tbProdutos = tbProdutos;
       this.tbVendas = tbVendas;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
       this.desconto = desconto;
       this.observacoes = observacoes;
    }
   
     @Id 

    
    @Column(name="id_vendas_produtos", unique=true, nullable=false)
    public int getIdVendasProdutos() {
        return this.idVendasProdutos;
    }
    
    public void setIdVendasProdutos(int idVendasProdutos) {
        this.idVendasProdutos = idVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produto")
    public TbProdutos getTbProdutos() {
        return this.tbProdutos;
    }
    
    public void setTbProdutos(TbProdutos tbProdutos) {
        this.tbProdutos = tbProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_venda")
    public TbVendas getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(TbVendas tbVendas) {
        this.tbVendas = tbVendas;
    }

    
    @Column(name="quantidade")
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_unitario", precision=10)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="desconto", precision=10)
    public double getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(double desconto) {
        this.desconto = desconto;
    }

    
    @Column(name="observacoes", length=65535)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }




}


